// Datos de ejemplo para la DEMO, con fechas relativas a hoy
import { Timestamp, __demoSeed, __demoStoreIsEmpty } from './firestore-shim'
import { addDaysISO, todayISO } from '../lib/dates'

const ANA = 'demo-ana'
const BRUNO = 'demo-bruno'
const HID = 'demo-hogar'
const H = `households/${HID}`

function ts(daysAgo: number, hourOffset = 0) {
  return Timestamp.fromMillis(Date.now() - daysAgo * 86_400_000 - hourOffset * 3_600_000)
}

export function seedDemoIfEmpty() {
  if (!__demoStoreIsEmpty()) return
  const today = todayISO()
  const day = (offset: number) => addDaysISO(today, offset)
  const month = today.slice(0, 7)

  __demoSeed({
    [`users/${ANA}`]: {
      householdId: HID,
      displayName: 'José',
      photoURL: null,
      email: 'ana@demo.hogarapp',
      createdAt: ts(30),
    },
    [`users/${BRUNO}`]: {
      householdId: HID,
      displayName: 'Ana',
      photoURL: null,
      email: 'bruno@demo.hogarapp',
      createdAt: ts(30),
    },
    'invites/DEMO42': { householdId: HID, createdBy: ANA, createdAt: ts(30) },
    [H]: {
      name: 'Casa de José y Ana',
      members: [ANA, BRUNO],
      memberProfiles: {
        [ANA]: { name: 'José', photoURL: null },
        [BRUNO]: { name: 'Ana', photoURL: null },
      },
      points: { [ANA]: 35, [BRUNO]: 50 },
      inviteCode: 'DEMO42',
      createdAt: ts(30),
    },

    [`${H}/tasks/t1`]: {
      title: 'Regar las plantas',
      assigneeUid: ANA,
      date: today,
      seriesId: null,
      done: false,
      points: 5,
      createdBy: BRUNO,
      createdAt: ts(2),
      completedAt: null,
      completedBy: null,
    },
    [`${H}/tasks/t2`]: {
      title: 'Llevar la ropa a la tintorería',
      assigneeUid: BRUNO,
      date: day(-1),
      seriesId: null,
      done: false,
      points: 10,
      createdBy: ANA,
      createdAt: ts(1),
      completedAt: null,
      completedBy: null,
    },
    [`${H}/tasks/t3`]: {
      title: 'Lavar los platos',
      assigneeUid: BRUNO,
      date: today,
      seriesId: null,
      done: true,
      points: 10,
      createdBy: ANA,
      createdAt: ts(4),
      completedAt: ts(1, 3),
      completedBy: BRUNO,
    },

    [`${H}/taskSeries/s1`]: {
      title: 'Cambiar las sábanas',
      assigneeUid: ANA,
      points: 15,
      startDate: day(-14),
      recurrence: { freq: 'weekly', interval: 2 },
      endDate: null,
      active: true,
      createdBy: ANA,
      createdAt: ts(14),
    },
    [`${H}/tasks/s1_${day(-14)}`]: {
      title: 'Cambiar las sábanas',
      assigneeUid: ANA,
      date: day(-14),
      seriesId: 's1',
      done: true,
      points: 15,
      createdBy: ANA,
      createdAt: ts(14),
      completedAt: ts(14),
      completedBy: ANA,
    },
    [`${H}/taskTemplates/cocinar`]: { title: 'Cocinar', points: 10, count: 12, lastUsedAt: ts(1) },
    [`${H}/taskTemplates/lavar-los-platos`]: { title: 'Lavar los platos', points: 10, count: 9, lastUsedAt: ts(0) },
    [`${H}/taskTemplates/regar-las-plantas`]: { title: 'Regar las plantas', points: 5, count: 6, lastUsedAt: ts(0) },
    [`${H}/taskTemplates/cambiar-las-sabanas`]: { title: 'Cambiar las sábanas', points: 15, count: 3, lastUsedAt: ts(14) },
    [`${H}/taskTemplates/sacar-la-basura`]: { title: 'Sacar la basura', points: 5, count: 20, lastUsedAt: ts(2) },

    [`${H}/fixedExpenses/f1`]: {
      name: 'Alquiler',
      amount: 420000,
      category: 'alquiler',
      dayOfMonth: 5,
      startDate: `${month}-05`,
      endDate: null,
      paidBy: BRUNO,
      remindDaysBefore: 3,
      active: true,
      createdBy: ANA,
      createdAt: ts(60),
    },
    [`${H}/fixedExpenses/f2`]: {
      name: 'Expensas',
      amount: 96000,
      category: 'hogar',
      dayOfMonth: Number(today.slice(8, 10)),
      startDate: today,
      endDate: null,
      paidBy: null,
      remindDaysBefore: 3,
      active: true,
      createdBy: BRUNO,
      createdAt: ts(60),
    },
    [`${H}/expenses/e0`]: {
      amount: 420000,
      description: 'Alquiler',
      category: 'alquiler',
      paidBy: BRUNO,
      date: `${month}-05`,
      kind: 'fijo',
      fixedExpenseId: 'f1',
      fixedDueDate: `${month}-05`,
      createdBy: BRUNO,
      createdAt: ts(20),
    },
    [`${H}/expenses/e1`]: {
      kind: 'variable',
      fixedExpenseId: null,
      fixedDueDate: null,
      amount: 48200,
      description: 'Supermercado semanal',
      category: 'supermercado',
      paidBy: ANA,
      date: `${month}-08`,
      createdBy: ANA,
      createdAt: ts(8),
    },
    [`${H}/expenses/e2`]: {
      kind: 'variable',
      fixedExpenseId: null,
      fixedDueDate: null,
      amount: 21000,
      description: 'Luz (Edesur)',
      category: 'servicios',
      paidBy: BRUNO,
      date: `${month}-12`,
      createdBy: BRUNO,
      createdAt: ts(6),
    },
    [`${H}/expenses/e3`]: {
      kind: 'variable',
      fixedExpenseId: null,
      fixedDueDate: null,
      amount: 15300,
      description: 'Pizzas del viernes',
      category: 'ocio',
      paidBy: BRUNO,
      date: day(-3) >= `${month}-01` ? day(-3) : `${month}-02`,
      createdBy: BRUNO,
      createdAt: ts(3),
    },

    [`${H}/shoppingItems/s1`]: {
      name: 'Yerba',
      nameNorm: 'yerba',
      addedBy: ANA,
      createdAt: ts(1),
      fromInventoryId: 'i2',
    },
    [`${H}/shoppingItems/s2`]: {
      name: 'Detergente',
      nameNorm: 'detergente',
      addedBy: BRUNO,
      createdAt: ts(0, 5),
      fromInventoryId: null,
    },
    [`${H}/shoppingItems/s3`]: {
      name: 'Pan lactal',
      nameNorm: 'pan lactal',
      addedBy: ANA,
      createdAt: ts(2),
      fromInventoryId: null,
    },

    [`${H}/products/yerba`]: { name: 'Yerba', nameNorm: 'yerba', count: 7, lastUsedAt: ts(1), location: 'despensa' },
    [`${H}/products/leche`]: { name: 'Leche', nameNorm: 'leche', count: 5, lastUsedAt: ts(4), location: 'heladera' },
    [`${H}/products/pan-lactal`]: { name: 'Pan lactal', nameNorm: 'pan lactal', count: 4, lastUsedAt: ts(2), location: null },
    [`${H}/products/queso-cremoso`]: { name: 'Queso cremoso', nameNorm: 'queso cremoso', count: 3, lastUsedAt: ts(9), location: 'heladera' },
    [`${H}/products/detergente`]: { name: 'Detergente', nameNorm: 'detergente', count: 2, lastUsedAt: ts(0), location: 'limpieza' },

    [`${H}/inventoryItems/i1`]: {
      name: 'Leche',
      nameNorm: 'leche',
      location: 'heladera',
      status: 'ok',
      updatedAt: ts(4),
      linkedShoppingItemId: null,
    },
    [`${H}/inventoryItems/i2`]: {
      name: 'Yerba',
      nameNorm: 'yerba',
      location: 'despensa',
      status: 'comprar',
      updatedAt: ts(1),
      linkedShoppingItemId: 's1',
    },
    [`${H}/inventoryItems/i3`]: {
      name: 'Huevos',
      nameNorm: 'huevos',
      location: 'heladera',
      status: 'ok',
      updatedAt: ts(6),
      linkedShoppingItemId: null,
    },

    [`${H}/inventoryItems/i4`]: {
      name: 'Lavandina',
      nameNorm: 'lavandina',
      location: 'limpieza',
      status: 'ok',
      updatedAt: ts(9),
      linkedShoppingItemId: null,
    },

    [`${H}/events/ev1`]: {
      title: 'Clase de cerámica',
      type: 'otro',
      startDate: day(-2),
      time: '19:00',
      recurrence: { freq: 'weekly', interval: 1 },
      endDate: null,
      remindDaysBefore: 1,
      notes: 'Taller de la vuelta',
      doneDates: [],
      createdBy: ANA,
      createdAt: ts(30),
    },
    [`${H}/events/ev2`]: {
      title: 'Turno dentista',
      type: 'salud',
      startDate: today,
      time: '17:30',
      recurrence: null,
      endDate: null,
      remindDaysBefore: 1,
      notes: '',
      doneDates: [],
      createdBy: ANA,
      createdAt: ts(10),
    },
    [`${H}/events/ev3`]: {
      title: 'Vienen los papás de Ana',
      type: 'visita',
      startDate: day(6),
      time: null,
      recurrence: null,
      endDate: null,
      remindDaysBefore: 3,
      notes: 'Comprar algo rico para la merienda',
      doneDates: [],
      createdBy: BRUNO,
      createdAt: ts(5),
    },

    [`${H}/planes/p1`]: {
      title: 'Cena en la parrilla nueva de Palermo',
      kind: 'plan',
      status: 'idea',
      notes: '',
      createdBy: ANA,
      createdAt: ts(7),
      doneAt: null,
    },
    [`${H}/planes/p2`]: {
      title: 'Severance',
      kind: 'cine',
      status: 'idea',
      notes: 'Dicen que la 2.ª temporada es tremenda',
      createdBy: BRUNO,
      createdAt: ts(3),
      doneAt: null,
    },
    [`${H}/planes/p3`]: {
      title: 'Finde en Tigre',
      kind: 'viaje',
      status: 'hecho',
      notes: 'Salió hermoso 💛',
      createdBy: ANA,
      createdAt: ts(25),
      doneAt: ts(12),
    },

    [`${H}/rewards/r1`]: {
      title: 'Elegís la peli del viernes',
      cost: 30,
      active: true,
      createdBy: ANA,
      createdAt: ts(20),
    },
    [`${H}/rewards/r2`]: {
      title: 'Desayuno a la cama',
      cost: 50,
      active: true,
      createdBy: BRUNO,
      createdAt: ts(18),
    },
    [`${H}/redemptions/rd1`]: {
      rewardId: 'r1',
      rewardTitle: 'Elegís la peli del viernes',
      cost: 30,
      redeemedBy: BRUNO,
      createdAt: ts(6),
    },

    [`${H}/contacts/c1`]: {
      name: 'Jorge',
      role: 'Plomero',
      phone: '11-5555-1234',
      notes: 'Recomendado del edificio',
      createdAt: ts(60),
    },
    [`${H}/contacts/c2`]: {
      name: 'Marta',
      role: 'Electricista',
      phone: '11-5555-9876',
      notes: '',
      createdAt: ts(45),
    },
  })
}
